# Documentation
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

# Depends on:
# - https://github.com/JS-DevTools/npm-publish
# - https://github.com/rickstaa/action-create-tag

# Usage in your workflow YML:
# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     needs: [lint, test]
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - uses: jerryjappinen/bonn/.github/actions/publish
#         with:
#           token: ${{ secrets.NPM_TOKEN }}

name: 'bonn-npm-publish'
description: 'Publishes your repo as package on npm. Uses the version number in package.json on npm and creates a version tag in the repo.'
inputs:
  token:
    description: 'NPM token that has access to the package. First set this up on npmjs.org, then add it as repository secret on GitHub.'
    required: true

# Pass through publish version info
# https://github.com/JS-DevTools/npm-publish#output-variables
outputs:
  type:
    value: ${{ steps.publish.outputs.type }}
  version:
    value: ${{ steps.publish.outputs.version }}
  old-version:
    value: ${{ steps.publish.outputs.old-version }}
  tag:
    value: ${{ steps.publish.outputs.tag }}
  access:
    value: ${{ steps.publish.outputs.access }}
  dry-run:
    value: ${{ steps.publish.outputs.dry-run }}

runs:
  using: "composite"
  steps:

    # Self-checkout
    - name: Initial checkout
      id: checkout
      uses: actions/checkout@v3

    # Setup
    - name: Node setup
      id: setup
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    # Install deps
    - name: Install dependencies
      id: install
      shell: bash
      run: npm install -f

    - name: Publish to npm
      id: publish
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ inputs.token }}

    - name: Create version tag
      id: tag
      if: steps.publish.outputs.type != 'none'
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "v${{ steps.publish.outputs.version }}"
        message: "Tag for ${{ steps.publish.outputs.version }}"
