# Documentation
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

# Usage in your workflow YML:
# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     needs: [lint, test]
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - uses: jerryjappinen/bonn/.github/actions/publish
#         with:
#           token: ${{ secrets.NPM_TOKEN }}

name: 'Bonn: publish'
description: 'Publishes your repo as package on npm. Uses the version number in package.json on npm and creates a version tag in the repo.'
inputs:
  token:
    description: 'NPM token that has access to the package. First set this up on npmjs.org, then add it as repository secret on GitHub.'
    required: true
runs:
  using: "composite"
  steps:

    # Setup
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    # Install deps
    - name: Install dependencies
      shell: bash
      run: npm install

    # Publish to npm
    - uses: actions/checkout@v3
      with:
        repository: JS-DevTools/npm-publish
    - name: Publish to npm
      id: publish
      uses: JS-DevTools/publish@v1
      with:
        token: ${{ inputs.token }}

    # Create tag in repo
    - uses: actions/checkout@v3
      with:
        repository: rickstaa/action-create-tag
    - name: Create version tag
      id: tag
      if: steps.publish.outputs.type != 'none'
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "v${{ steps.publish.outputs.version }}"
        message: "Tag for ${{ steps.publish.outputs.version }}"
