name: main
on: push

jobs:

  # FIXME:
  # - I'd like to have a generic setup action that the others use
  # - But build output is not easily reused by each job
  # - Now I have to duplicate the setup code in each section, and reinstall for each job
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version-file: '.nvmrc'
  #         cache: 'npm'
  #     - run: npm install

  lint:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install
      - run: npm run test

  # Add repository secret on GitHub
  publish:
    runs-on: ubuntu-latest
    # needs: [setup, lint, test]
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
