name: main
on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ../actions/run
        with:
          script: lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ../actions/run
        with:
          script: test

  publish:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: ../actions/publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
